#server 
server.port = 8080

#MongoDB
spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = arrache_quality_db

#App name
spring.application.name = arrache-arrache_quality

spring.security.user.name = admin
spring.security.user.password = admin
